Resources:
  # here we define a SSH security group that will be used in the entire company
  MyCompanyWideSSHSecurityGroup:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22 # GOLDEN RULE
      SecurityGroupIngress:
        # we have a lot of rules because it's a perfect security group
        # finance team network
        - CidrIp: 10.0.48.0/24
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
          # marketing team network
        - CidrIp: 10.0.112.0/24
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
          # application team support network
        - CidrIp: 10.0.176.0/24
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
Resources:
  fasolaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: 'Due-18-Practice'
  myinstance:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: us-east-1
      ImageID: ami-033b95fb8079dc481